In [52]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
import pickle

In [53]:
# # Load the dataset

data = pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [54]:
# Preprocess  the data 

data = data.drop(['RowNumber' , 'CustomerId' , 'Surname'] , axis=1)
data

     CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0            619    France  Female  ...               1        101348.88       1
1            608     Spain  Female  ...               1        112542.58       0
2            502    France  Female  ...               0        113931.57       1
3            699    France  Female  ...               0         93826.63       0
4            850     Spain  Female  ...               1         79084.10       0
..           ...       ...     ...  ...             ...              ...     ...
235          771    France    Male  ...               0         96270.64       0
236          516    France    Male  ...               1        101699.77       0
237          709    France  Female  ...               1         42085.58       1
238          772   Germany    Male  ...               0         92888.52       1
239          792    France  Female  ...               0         38190.78       0

[240 rows x 11 columns]

In [55]:
# Encoding Categorical Variables

label_encoder_gender = LabelEncoder()
data['Gender'] =label_encoder_gender.fit_transform(data['Gender'])
data

     CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0            619    France       0  ...               1        101348.88       1
1            608     Spain       0  ...               1        112542.58       0
2            502    France       0  ...               0        113931.57       1
3            699    France       0  ...               0         93826.63       0
4            850     Spain       0  ...               1         79084.10       0
..           ...       ...     ...  ...             ...              ...     ...
235          771    France       1  ...               0         96270.64       0
236          516    France       1  ...               1        101699.77       0
237          709    France       0  ...               1         42085.58       1
238          772   Germany       1  ...               0         92888.52       1
239          792    France       0  ...               0         38190.78       0

[240 rows x 11 columns]

In [56]:
#Onehot encode "Geography"

from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [57]:
onehot_encoder_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [58]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray() , columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

     Geography_France  Geography_Germany  Geography_Spain
0                 1.0                0.0              0.0
1                 0.0                0.0              1.0
2                 1.0                0.0              0.0
3                 1.0                0.0              0.0
4                 0.0                0.0              1.0
..                ...                ...              ...
235               1.0                0.0              0.0
236               1.0                0.0              0.0
237               1.0                0.0              0.0
238               0.0                1.0              0.0
239               1.0                0.0              0.0

[240 rows x 3 columns]

In [59]:
## Combine one hot encoder column with the original data 
data = pd.concat([data.drop('Geography' , axis=1) , geo_encoded_df] , axis=1)
data

     CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0            619       0  ...                0.0              0.0
1            608       0  ...                0.0              1.0
2            502       0  ...                0.0              0.0
3            699       0  ...                0.0              0.0
4            850       0  ...                0.0              1.0
..           ...     ...  ...                ...              ...
235          771       1  ...                0.0              0.0
236          516       1  ...                0.0              0.0
237          709       0  ...                0.0              0.0
238          772       1  ...                1.0              0.0
239          792       0  ...                0.0              0.0

[240 rows x 13 columns]

In [60]:
## Save the encoders and scaler 
with open('label_encoder_gender.pkl' , 'wb') as file:
    pickle.dump(label_encoder_gender , file)

with open('onehot_encoder_geo.pkl' , 'wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [65]:
## Divide the dataset into indenpent and dependent feature 
X = data.drop('Exited' , axis = 1)
y = data['Exited']

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2 , random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.63049937, -0.98963703, -0.3176202 , ..., -0.91986621,
        -0.6336086 ,  1.70832296],
       [ 0.93778138,  1.01047149, -0.3176202 , ..., -0.91986621,
         1.57826141, -0.58536941],
       [-1.5926348 ,  1.01047149, -0.42312726, ...,  1.08711461,
        -0.6336086 , -0.58536941],
       ...,
       [-1.15967386, -0.98963703, -0.21211314, ...,  1.08711461,
        -0.6336086 , -0.58536941],
       [ 1.05323763, -0.98963703,  1.79252092, ..., -0.91986621,
         1.57826141, -0.58536941],
       [ 0.89929596,  1.01047149, -0.73964842, ...,  1.08711461,
        -0.6336086 , -0.58536941]], shape=(192, 12))

In [66]:
X_test

array([[ 1.93840222e+00, -9.89637026e-01, -1.09903183e-03,
        -7.82352433e-02, -1.24829028e+00, -9.07392872e-01,
         7.23746864e-01,  1.07578035e+00,  1.46858010e+00,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [ 1.70748972e+00,  1.01047149e+00,  1.26498564e+00,
         6.20423674e-01, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01,  1.07578035e+00, -1.59144206e+00,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [ 1.19755794e+00,  1.01047149e+00, -9.50662536e-01,
         9.69753132e-01, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01,  1.07578035e+00,  1.20445374e+00,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-1.59263480e+00,  1.01047149e+00, -3.17620200e-01,
         1.31908259e+00,  2.58789019e-01, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01, -5.09114559e-02,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [ 2.45043867e-01, -9.89637026e-01,  2.84759148e+00,
        -1.47555308e+00, -1.24829028e+00, -9.07392872e-01,
         7.23746864e-01,  1.07578035e+00,  1.29691740e+00,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [-1.58301345e+00,  1.01047149e+00,  6.31943304e-01,
         1.66841205e+00,  8.55794691e-01, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01, -1.67054959e+00,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [-5.11134447e-03,  1.01047149e+00, -1.05616959e+00,
         6.20423674e-01,  1.26898368e+00, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01, -1.26197723e+00,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [ 1.01475221e+00,  1.01047149e+00, -1.68921193e+00,
        -7.76894160e-01,  7.27110642e-01, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01,  4.52220258e-01,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [ 3.79742827e-01,  1.01047149e+00, -1.16167665e+00,
        -1.12622362e+00,  9.36889303e-01, -9.07392872e-01,
         7.23746864e-01,  1.07578035e+00, -5.28719660e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [ 1.42847044e+00,  1.01047149e+00,  1.47599975e+00,
        -1.12622362e+00, -1.24829028e+00, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01,  9.77532274e-01,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [ 1.26490742e+00, -9.89637026e-01, -6.34141368e-01,
        -4.27564702e-01,  5.28068762e-01,  8.00640769e-01,
         7.23746864e-01,  1.07578035e+00,  4.15581861e-01,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [-1.59263480e+00,  1.01047149e+00, -3.17620200e-01,
        -4.27564702e-01,  7.95929802e-01, -9.07392872e-01,
         7.23746864e-01,  1.07578035e+00, -1.41339988e+00,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [ 7.35732936e-01,  1.01047149e+00, -1.05616959e+00,
         1.31908259e+00,  1.25948881e+00,  8.00640769e-01,
        -1.38169856e+00,  1.07578035e+00, -1.90092389e-02,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [ 2.16179804e-01, -9.89637026e-01,  1.04408024e-01,
        -1.12622362e+00, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01, -9.29557782e-01, -1.06306284e+00,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [ 2.93150638e-01,  1.01047149e+00, -2.12113144e-01,
         1.31908259e+00,  4.75623041e-01, -9.07392872e-01,
        -1.38169856e+00,  1.07578035e+00, -1.36857532e+00,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [ 6.68383456e-01,  1.01047149e+00, -5.28634312e-01,
        -7.76894160e-01, -6.79825540e-01, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01, -8.39949305e-01,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [-1.25588740e+00,  1.01047149e+00, -6.34141368e-01,
         9.69753132e-01, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01, -9.29557782e-01, -1.12829070e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-2.74509265e-01,  1.01047149e+00,  7.37450360e-01,
        -7.76894160e-01,  1.07529404e+00,  8.00640769e-01,
        -1.38169856e+00,  1.07578035e+00, -6.56227707e-01,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [ 6.87626164e-01,  1.01047149e+00,  4.20929192e-01,
         9.69753132e-01, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01, -9.29557782e-01,  1.35111505e+00,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [-2.04483845e+00,  1.01047149e+00,  4.20929192e-01,
         1.31908259e+00,  1.22909702e+00, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01,  1.35484918e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-1.87917076e-01,  1.01047149e+00,  1.89802798e+00,
        -1.82488254e+00,  1.16259853e+00, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01, -9.57884171e-01,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [ 7.83839707e-01, -9.89637026e-01, -1.47819782e+00,
         2.71094215e-01, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01,  1.07578035e+00, -8.21733427e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [ 1.21680065e+00,  1.01047149e+00,  1.04408024e-01,
        -7.82352433e-02, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01, -9.29557782e-01, -1.05703343e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-5.15043122e-01, -9.89637026e-01,  1.04408024e-01,
        -7.76894160e-01, -1.24829028e+00,  2.50867441e+00,
         7.23746864e-01, -9.29557782e-01,  6.56034558e-01,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [-1.29437282e+00, -9.89637026e-01, -8.45155480e-01,
        -1.82488254e+00, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01,  1.07578035e+00,  4.85139993e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [ 1.05323763e+00, -9.89637026e-01, -6.34141368e-01,
         6.20423674e-01, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01, -9.29557782e-01, -2.22033515e-01,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [-1.12118844e+00,  1.01047149e+00, -7.39648424e-01,
         2.71094215e-01,  4.07864459e-01,  8.00640769e-01,
        -1.38169856e+00, -9.29557782e-01, -3.82996252e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-6.88227499e-01,  1.01047149e+00,  6.31943304e-01,
         1.31908259e+00, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01, -9.29557782e-01,  8.13505224e-02,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [ 6.20276684e-01, -9.89637026e-01, -2.12113144e-01,
         6.20423674e-01, -1.24829028e+00, -9.07392872e-01,
        -1.38169856e+00,  1.07578035e+00, -1.03954928e+00,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-1.01535354e+00,  1.01047149e+00, -1.06606088e-01,
        -1.12622362e+00,  8.23342950e-01, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01, -6.47616934e-02,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [ 1.23604336e+00,  1.01047149e+00,  3.15422136e-01,
         1.31908259e+00,  4.21025809e-01, -9.07392872e-01,
        -1.38169856e+00,  1.07578035e+00, -6.51609066e-01,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [ 1.25528607e+00,  1.01047149e+00, -8.45155480e-01,
        -4.27564702e-01, -1.24829028e+00,  8.00640769e-01,
         7.23746864e-01, -9.29557782e-01, -9.14561074e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-6.49742082e-01,  1.01047149e+00, -1.37269076e+00,
        -7.76894160e-01, -1.24829028e+00,  8.00640769e-01,
        -1.38169856e+00,  1.07578035e+00,  3.80955061e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [ 1.28415013e+00, -9.89637026e-01,  7.37450360e-01,
        -1.47555308e+00,  1.38408397e+00,  8.00640769e-01,
         7.23746864e-01, -9.29557782e-01,  1.24307013e+00,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [-5.53528539e-01,  1.01047149e+00,  7.37450360e-01,
         2.71094215e-01, -1.24829028e+00, -9.07392872e-01,
        -1.38169856e+00, -9.29557782e-01,  9.69966209e-01,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [ 2.93150638e-01, -9.89637026e-01, -1.79471898e+00,
         9.69753132e-01,  3.48715983e-01, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01, -1.45115075e+00,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-1.59263480e+00,  1.01047149e+00,  2.09915080e-01,
        -1.47555308e+00, -1.24829028e+00,  8.00640769e-01,
        -1.38169856e+00, -9.29557782e-01,  2.17024046e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-2.45645202e-01,  1.01047149e+00,  5.26436248e-01,
        -1.47555308e+00,  7.84418815e-01, -9.07392872e-01,
         7.23746864e-01,  1.07578035e+00,  1.89691353e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-2.19878012e+00, -9.89637026e-01,  3.15422136e-01,
         1.66841205e+00,  7.35354993e-01,  8.00640769e-01,
         7.23746864e-01, -9.29557782e-01, -7.07008333e-02,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [-1.54452803e+00, -9.89637026e-01, -3.17620200e-01,
         6.20423674e-01,  9.24946326e-01, -9.07392872e-01,
         7.23746864e-01,  1.07578035e+00, -1.29460915e+00,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [-3.70722807e-01,  1.01047149e+00, -8.45155480e-01,
         9.69753132e-01,  1.67885246e+00,  8.00640769e-01,
         7.23746864e-01,  1.07578035e+00, -1.73187451e+00,
        -9.19866211e-01, -6.33608597e-01,  1.70832296e+00],
       [-7.94062396e-01,  1.01047149e+00,  4.20929192e-01,
        -1.12622362e+00,  3.78994134e-01, -9.07392872e-01,
        -1.38169856e+00, -9.29557782e-01, -2.68968593e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-1.40982907e+00,  1.01047149e+00,  4.20929192e-01,
        -7.76894160e-01,  1.21994502e+00, -9.07392872e-01,
         7.23746864e-01,  1.07578035e+00, -8.43773786e-01,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [ 8.14808441e-02,  1.01047149e+00,  2.10904209e+00,
        -1.47555308e+00,  9.04404769e-01, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01, -1.67701300e+00,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [ 1.09172304e+00, -9.89637026e-01, -5.28634312e-01,
         6.20423674e-01, -1.24829028e+00,  8.00640769e-01,
        -1.38169856e+00, -9.29557782e-01, -3.34475439e-01,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01],
       [-6.11256665e-01, -9.89637026e-01, -4.23127256e-01,
        -1.47555308e+00,  4.01635740e-01, -9.07392872e-01,
         7.23746864e-01, -9.29557782e-01,  1.38350478e-01,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [ 1.48830324e-01,  1.01047149e+00, -7.39648424e-01,
         1.31908259e+00,  7.84058904e-01,  8.00640769e-01,
         7.23746864e-01,  1.07578035e+00,  6.45780964e-01,
        -9.19866211e-01,  1.57826141e+00, -5.85369407e-01],
       [ 1.97688764e+00,  1.01047149e+00, -2.12113144e-01,
         6.20423674e-01, -1.24829028e+00, -9.07392872e-01,
         7.23746864e-01,  1.07578035e+00, -1.06148313e+00,
         1.08711461e+00, -6.33608597e-01, -5.85369407e-01]])

In [67]:
with open('scaler.pkl' , 'wb') as file:
    pickle.dump(scaler , file)

In [68]:
data

     CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0            619       0  ...                0.0              0.0
1            608       0  ...                0.0              1.0
2            502       0  ...                0.0              0.0
3            699       0  ...                0.0              0.0
4            850       0  ...                0.0              1.0
..           ...     ...  ...                ...              ...
235          771       1  ...                0.0              0.0
236          516       1  ...                0.0              0.0
237          709       0  ...                0.0              0.0
238          772       1  ...                1.0              0.0
239          792       0  ...                0.0              0.0

[240 rows x 13 columns]

In [86]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping , TensorBoard
import datetime

In [87]:
model = Sequential([
    Dense(64,activation='relu', input_shape=(X_train.shape[1],)) , ## First Hidden Layer with input Layer
    Dense(32 , activation='relu'),  ## Hidden Layer 2
    Dense(1, activation='sigmoid')  ## Output Layer 
    
])

e:\Neural-Network-From-Scratch\venv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [88]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [99]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [100]:
## Complie the model
model.compile(optimizer=opt , loss="binary_crossentropy" , metrics=['accuracy'])

In [101]:
## setup up the tensorborad
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
## setup tensorboard
log_dir = 'logs/fit' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)
log_dir='logs/fit' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir , histogram_freq=1)

In [102]:
### Setup Early Stopping 
early_stopping_callback = EarlyStopping(monitor='val_loss' , patience=5 , restore_best_weights=True)

In [ ]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test), 
    epochs=100,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 9s 412ms/step - accuracy: 0.7396 - loss: 0.5533 - val_accuracy: 0.7292 - val_loss: 0.7189
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.8177 - loss: 0.4031 - val_accuracy: 0.7708 - val_loss: 0.5666
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8385 - loss: 0.3463 - val_accuracy: 0.7292 - val_loss: 0.5426
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8698 - loss: 0.3145 - val_accuracy: 0.7500 - val_loss: 0.6320
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8646 - loss: 0.2807 - val_accuracy: 0.7500 - val_loss: 0.7419
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8750 - loss: 0.2519 - val_accuracy: 0.7500 - val_loss: 0.8083
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8906 - loss: 0.2232 - val_accuracy: 0.7500 - val_loss: 0.8323
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9271 - loss: 0.1869 - val_accuracy: 0.7500 - val_loss: 0.9199

In [108]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.