In [37]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [38]:
## Load the trained model , scaler , picker , onehot
model = load_model('model.h5')

# load the enocders and scaler

with open('onehot_encoder_geo.pkl' , 'rb') as file:
    label_encoder_geo = pickle.load(file)

with open('label_encoder_gender.pkl' ,'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('scaler.pkl' , 'rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [39]:
input_data = {
    'CreditScore': 619,
    'Geography': 'France',
    'Gender': 'Female',
    'Age': 42,
    'Tenure': 2,
    'Balance': 0.0,
    'NumOfProducts': 1,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 101348.88
}

In [40]:
geo_encoded = label_encoder_geo.transform(
    [[input_data['Geography']]]
).toarray()

geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=label_encoder_geo.get_feature_names_out(['Geography'])
)

geo_encoded_df

e:\Neural-Network-From-Scratch\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [41]:
import pandas as pd

input_df = pd.DataFrame([input_data])

In [42]:
input_df = pd.concat(
    [input_df.reset_index(drop=True), geo_encoded_df],
    axis=1
)

In [43]:
input_df.drop('Geography', axis=1, inplace=True)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,Female,42,2,0.0,1,1,1,101348.88,1.0,0.0,0.0

In [44]:
input_df['Gender'] = label_encoder_gender.transform(
    input_df["Gender"]
)

In [45]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.0,1,1,1,101348.88,1.0,0.0,0.0

In [46]:
##Scalin the input data 
input_scales = scaler.transform(input_df)
input_scales

array([[-0.2456452 , -0.98963703,  0.42092919, -1.12622362, -1.24829028,
        -0.90739287,  0.72374686,  1.07578035, -0.01818302,  1.08711461,
        -0.6336086 , -0.58536941]])

In [49]:
#Prediction churn
prediction = model.predict(input_scales)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

In [51]:
prodiction_proba = prediction[0][0]
prodiction_proba

np.float32(0.28063464)

In [52]:
if prodiction_proba >0.5:
    print("The customer is likely to churn.")

else:
    print("The customer is not likely to churn")

The customer is not likely to churn